### PR TITLE
Initial commit: Create Template custom Widget project

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@willingc @jdfreder this is an example custom widget project meant to serve as a template for widget authors.

@minrk suggest we license this as `CC-0` instead of BSD. 

Other suggestion by Min: make a cookiecutter template for such a project.

### CODE REVIEW

**Comment by willingc** [comment]
@SylvainCorlay Super!

@minrk's suggestion to make a CookieCuttter template :smile:

**Comment by blink1073** [comment]
I'd suggest a top level README that describes overall what the moving pieces are (like why certain files are needed).

**Comment by SylvainCorlay** [comment]
@minrk I changed the license to CC0. Will do the cookie cutter in the next PR. Are you fine with merging as is? I would like to refer to this to respond to some widget authors.

**Comment by SylvainCorlay** [comment]
cc @jdfreder

**Pull request merged**
